import { useGoogleLogin } from "@react-oauth/google";
import axios from "axios";
import { useState } from "react";

export default function CalendarButton({plan}) {
    const [loading,setLoading] = useState(false);
    if(!plan){

return null;

}


const login = useGoogleLogin({

scope:
"https://www.googleapis.com/auth/calendar.events",


onSuccess: async(tokenResponse)=>{
setLoading(true);

try{


for(const day of plan.days){


for(const task of day.tasks){


await axios.post(

"https://www.googleapis.com/calendar/v3/calendars/primary/events",

{


summary: task,

description:
`Generated by Aheadify - ${day.day}`,


start:{

dateTime:
new Date(
Date.now() + 3600000
).toISOString(),

timeZone:
"Asia/Kolkata"

},


end:{

dateTime:
new Date(
Date.now()+3600000
).toISOString(),

timeZone:
"Asia/Kolkata"

}


},

{

headers:{

Authorization:
`Bearer ${tokenResponse.access_token}`

}

}

);


}


}


alert(
"Tasks added to Google Calendar 🎉"
);
setLoading(false);


}

catch(err){

console.log(err);

alert(
"Calendar creation failed"
);

}

finally{

setLoading(false);

}


}


});


return(

<button

onClick={login}

className="bg-blue-600 text-white px-6 py-3 rounded-xl"

>

{
loading
?
"Adding..."
:
"Add to Google Calendar 📅"
}
</button>

)

}