import Sidebar from "../components/Sidebar";
import Navbar from "../components/Navbar";
import { CalendarDays, Clock3, Plus } from "lucide-react";
import { useEffect, useState } from "react";

import { db } from "../firebase";

import {
  collection,
  query,
  where,
  getDocs
} from "firebase/firestore";


export default function Calendar() {

  const [schedule, setSchedule] = useState([]);


  const user =
    JSON.parse(localStorage.getItem("user"));

  useEffect(() => {


    async function fetchSchedule() {


      const q = query(

        collection(db, "tasks"),

        where(
          "uid",
          "==",
          user.uid
        )

      );


      const snapshot = await getDocs(q);



      const data =
        snapshot.docs.map(doc => ({

          id: doc.id,

          ...doc.data(),

          time: "09:00 AM"


        }));



      setSchedule(data);



    }


    fetchSchedule();



  }, []);
  return (
    <div className="min-h-screen bg-slate-100 flex">
      <Sidebar />

      <div className="flex-1">
        <Navbar />

        <div className="p-8">

          <div className="flex justify-between items-center mb-8">
            <div>
              <h1 className="text-4xl font-bold">
                AI Calendar
              </h1>

              <p className="text-gray-500 mt-2">
                Smart timeline generated by Aheadify AI
              </p>
            </div>

            <button className="bg-indigo-600 hover:bg-indigo-700 text-white px-6 py-3 rounded-xl flex gap-2">
              <Plus size={20} />
              Add Event
            </button>
          </div>

          <div className="grid lg:grid-cols-3 gap-6">

            <div className="lg:col-span-2 bg-white rounded-3xl shadow p-8">

              <div className="flex items-center gap-3 mb-8">
                <CalendarDays className="text-indigo-600" />
                <h2 className="text-2xl font-bold">
                  Today's Timeline
                </h2>
              </div>

              <div className="space-y-5">

                {
                  schedule.length === 0 && (

                    <p className="text-gray-500">
                      No tasks scheduled yet. Generate a plan first.
                    </p>

                  )
                }

                {schedule.map((item, index) => (
                  <div
                    key={index}
                    className={`border-l-4 rounded-xl p-5 ${item.color}`}
                  >
                    <div className="flex justify-between">

                      <div>
                        <h3 className="font-semibold text-lg">
                          {item.title}
                        </h3>

                        <p className="text-gray-600 mt-2 flex gap-2 items-center">
                          <Clock3 size={16} />
                          {item.time}
                        </p>
                      </div>

                    </div>
                  </div>
                ))}

              </div>

            </div>

            <div className="space-y-6">

              <div className="bg-white rounded-3xl shadow p-6">

                <h2 className="text-2xl font-bold mb-5">
                  Today's Goal
                </h2>

                <div className="w-full bg-gray-200 rounded-full h-4">

                  <div className="bg-indigo-600 h-4 rounded-full w-3/4"></div>

                </div>

                <p className="mt-4 text-gray-500">
                  75% Completed
                </p>

              </div>

              <div className="bg-gradient-to-r from-indigo-600 to-purple-600 text-white rounded-3xl p-6">

                <h2 className="text-2xl font-bold">
                  AI Suggestion
                </h2>

                <p className="mt-4">
                  Finish Frontend before lunch.
                  Backend can be shifted to evening.
                </p>

              </div>

            </div>

          </div>

        </div>
      </div>
    </div>
  );
}